<?php

namespace App\Support;

class LanguageCatalog
{
    public static function languages(): array
    {
        return [
            ['name' => 'Arabic', 'native_name' => 'Arabic', 'code' => 'ar', 'icon' => 'AE'],
            ['name' => 'Chinese', 'native_name' => 'Chinese', 'code' => 'zh', 'icon' => 'CN'],
            ['name' => 'Czech', 'native_name' => 'Czech', 'code' => 'cs', 'icon' => 'CZ'],
            ['name' => 'Danish', 'native_name' => 'Danish', 'code' => 'da', 'icon' => 'DK'],
            ['name' => 'Dutch', 'native_name' => 'Dutch', 'code' => 'nl', 'icon' => 'NL'],
            ['name' => 'English', 'native_name' => 'English', 'code' => 'en', 'icon' => 'US'],
            ['name' => 'French', 'native_name' => 'French', 'code' => 'fr', 'icon' => 'FR'],
            ['name' => 'German', 'native_name' => 'German', 'code' => 'de', 'icon' => 'DE'],
            ['name' => 'Greek', 'native_name' => 'Greek', 'code' => 'el', 'icon' => 'GR'],
            ['name' => 'Gujarati', 'native_name' => 'Gujarati', 'code' => 'gu', 'icon' => 'IN'],
            ['name' => 'Hindi', 'native_name' => 'Hindi', 'code' => 'hi', 'icon' => 'IN'],
            ['name' => 'Indonesian', 'native_name' => 'Indonesian', 'code' => 'id', 'icon' => 'ID'],
            ['name' => 'Italian', 'native_name' => 'Italian', 'code' => 'it', 'icon' => 'IT'],
            ['name' => 'Japanese', 'native_name' => 'Japanese', 'code' => 'ja', 'icon' => 'JP'],
            ['name' => 'Norwegian', 'native_name' => 'Norwegian', 'code' => 'no', 'icon' => 'NO'],
            ['name' => 'Polish', 'native_name' => 'Polish', 'code' => 'pl', 'icon' => 'PL'],
            ['name' => 'Portuguese', 'native_name' => 'Portuguese', 'code' => 'pt', 'icon' => 'PT'],
            ['name' => 'Romanian', 'native_name' => 'Romanian', 'code' => 'ro', 'icon' => 'RO'],
            ['name' => 'Russian', 'native_name' => 'Russian', 'code' => 'ru', 'icon' => 'RU'],
            ['name' => 'Spanish', 'native_name' => 'Spanish', 'code' => 'es', 'icon' => 'ES'],
            ['name' => 'Bengali', 'native_name' => 'Bengali', 'code' => 'bn', 'icon' => 'BD'],
        ];
    }

    public static function keys(): array
    {
        return [
            'Dashboard' => 'Dashboard',
            'Permission' => 'Permission',
            'Languages' => 'Languages',
            'Translations' => 'Translations',
            'Slides' => 'Slides',
            'Users' => 'Users',
            'Admin' => 'Admin',
            'Vendor' => 'Vendor',
            'Vendor Dashboard' => 'Vendor Dashboard',
            'Reseller' => 'Reseller',
            'Reseller Dashboard' => 'Reseller Dashboard',
            'Rider' => 'Rider',
            'Rider Dashboard' => 'Rider Dashboard',
            'Role' => 'Role',
            'Consignment' => 'Consignment',
            'Consignments' => 'Consignments',
            'Products' => 'Products',
            'My Shop' => 'My Shop',
            'Your Products' => 'Your Products',
            'Add Products' => 'Add Products',
            'Resel Product' => 'Resel Product',
            'Vendor Shop' => 'Vendor Shop',
            'Sel & Earn' => 'Sel & Earn',
            'Categories' => 'Categories',
            'Orders' => 'Orders',
            'ViP Package' => 'ViP Package',
            'ViP Users' => 'ViP Users',
            'Carousel' => 'Carousel',
            'Static Slider' => 'Static Slider',
            'Settings' => 'Settings',
            'Star System' => 'Star System',
            'Level-up History' => 'Level-up History',
            'Developer' => 'Developer',
            'Management' => 'Management',
            'Management TM' => 'Management TM',
            'Store' => 'Store',
            'Deposit' => 'Deposit',
            'Sell' => 'Sell',
            'Comission' => 'Comission',
            'Withdraw' => 'Withdraw',
            'Shops' => 'Shops',
            'Menu' => 'Menu',
            'Links' => 'Links',
            'Account' => 'Account',
            'About Us' => 'About Us',
            'Contact Us' => 'Contact Us',
            'Earn' => 'Earn',
            'Privacy Policy' => 'Privacy Policy',
            'Return & Refund' => 'Return & Refund',
            'Terms & Conditions' => 'Terms & Conditions',
            'Register' => 'Register',
            'Mail Us' => 'Mail Us',
            'Information' => 'Information',
            'DBID No' => 'DBID No',
            'Trade License' => 'Trade License',
            'All Rights Reserved' => 'All Rights Reserved',
            'Search Product By Title or Tags' => 'Search Product By Title or Tags',
            'Search categories...' => 'Search categories...',
            'No category found' => 'No category found',
            'Wallet' => 'Wallet',
            'Add Balance' => 'Add Balance',
            'Visit Website' => 'Visit Website',
            'Notice' => 'Notice',
            'Back to User Dash' => 'Back to User Dash',
            'Back to User Panel' => 'Back to User Panel',
            'My Rider' => 'My Rider',
            'User Panel' => 'User Panel',
            'Order' => 'Order',
            'Profile' => 'Profile',
            'Request Vendor' => 'Request Vendor',
            'Request Reseller' => 'Request Reseller',
            'Log Out' => 'Log Out',
            'Login' => 'Login',
            'View All' => 'View All',
            'New Products' => 'New Products',
            'Today Products' => 'Today Products',
            'Recommended Products' => 'Recommended Products',
            'Top Sales' => 'Top Sales',
            'Mega Deals' => 'Mega Deals',
            'Womens Products' => 'Womens Products',
            'Medicine Products' => 'Medicine Products',
            'Food Products' => 'Food Products',
            'Save Translation' => 'Save Translation',
            'Search modules...' => 'Search modules...',
            'Icon' => 'Icon',
            'Language' => 'Language',
            'Progress' => 'Progress',
            'Done' => 'Done',
            'Total' => 'Total',
            'Actions' => 'Actions',
        ];
    }
}
